chartsForReadme:
	stack build && stack ghc -- ChartsForReadme.hs --make && ./ChartsForReadme

ColorMatrixExample: ColorMatrixExample.hs
	stack build && stack ghc -- ColorMatrixExample.hs --make && ./ColorMatrixExample

Shared: Shared.hs
	stack build && stack ghc -- Shared.hs

Palette: Palette.hs
	stack build && stack ghc -- Palette.hs --make && ./Palette

Cushion: Cushion.hs
	stack build && stack ghc -- Cushion.hs --make && ./Cushion
